/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakatGuideRouteImport } from './routes/zakat-guide'
import { Route as ZakatCalculatorRouteImport } from './routes/zakat-calculator'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as MyMembershipRouteImport } from './routes/my-membership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VCodeRouteImport } from './routes/v.$code'
import { Route as MCodeRouteImport } from './routes/m.$code'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminSmsRouteImport } from './routes/admin.sms'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminHelpRequestsRouteImport } from './routes/admin.help-requests'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFoundationRouteImport } from './routes/admin.foundation'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminDistributionSlipsRouteImport } from './routes/admin.distribution-slips'
import { Route as AdminContactMessagesRouteImport } from './routes/admin.contact-messages'
import { Route as AdminCommitteeRouteImport } from './routes/admin.committee'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminActivitiesRouteImport } from './routes/admin.activities'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const ZakatGuideRoute = ZakatGuideRouteImport.update({
  id: '/zakat-guide',
  path: '/zakat-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatCalculatorRoute = ZakatCalculatorRouteImport.update({
  id: '/zakat-calculator',
  path: '/zakat-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMembershipRoute = MyMembershipRouteImport.update({
  id: '/my-membership',
  path: '/my-membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VCodeRoute = VCodeRouteImport.update({
  id: '/v/$code',
  path: '/v/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MCodeRoute = MCodeRouteImport.update({
  id: '/m/$code',
  path: '/m/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSmsRoute = AdminSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRequestsRoute = AdminHelpRequestsRouteImport.update({
  id: '/help-requests',
  path: '/help-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoundationRoute = AdminFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistributionSlipsRoute = AdminDistributionSlipsRouteImport.update({
  id: '/distribution-slips',
  path: '/distribution-slips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactMessagesRoute = AdminContactMessagesRouteImport.update({
  id: '/contact-messages',
  path: '/contact-messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommitteeRoute = AdminCommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivitiesRoute = AdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AdminRoute,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActivitiesRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-membership': typeof MyMembershipRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
  '/zakat-guide': typeof ZakatGuideRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/distribution-slips': typeof AdminDistributionSlipsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/foundation': typeof AdminFoundationRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help-requests': typeof AdminHelpRequestsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/m/$code': typeof MCodeRoute
  '/v/$code': typeof VCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-membership': typeof MyMembershipRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
  '/zakat-guide': typeof ZakatGuideRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/distribution-slips': typeof AdminDistributionSlipsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/foundation': typeof AdminFoundationRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help-requests': typeof AdminHelpRequestsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/m/$code': typeof MCodeRoute
  '/v/$code': typeof VCodeRoute
  '/admin': typeof AdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/donations': typeof DonationsRoute
  '/events': typeof EventsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-membership': typeof MyMembershipRoute
  '/notices': typeof NoticesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/track': typeof TrackRoute
  '/zakat-calculator': typeof ZakatCalculatorRoute
  '/zakat-guide': typeof ZakatGuideRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/activities/new': typeof ActivitiesNewRoute
  '/admin/activities': typeof AdminActivitiesRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/committee': typeof AdminCommitteeRoute
  '/admin/contact-messages': typeof AdminContactMessagesRoute
  '/admin/distribution-slips': typeof AdminDistributionSlipsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/foundation': typeof AdminFoundationRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/help-requests': typeof AdminHelpRequestsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sms': typeof AdminSmsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/m/$code': typeof MCodeRoute
  '/v/$code': typeof VCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/donations'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/help'
    | '/login'
    | '/my-membership'
    | '/notices'
    | '/reset-password'
    | '/track'
    | '/zakat-calculator'
    | '/zakat-guide'
    | '/membership'
    | '/activities/new'
    | '/admin/activities'
    | '/admin/activity-logs'
    | '/admin/committee'
    | '/admin/contact-messages'
    | '/admin/distribution-slips'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/foundation'
    | '/admin/gallery'
    | '/admin/help-requests'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/volunteers'
    | '/m/$code'
    | '/v/$code'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/donate'
    | '/donations'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/help'
    | '/login'
    | '/my-membership'
    | '/notices'
    | '/reset-password'
    | '/track'
    | '/zakat-calculator'
    | '/zakat-guide'
    | '/membership'
    | '/activities/new'
    | '/admin/activities'
    | '/admin/activity-logs'
    | '/admin/committee'
    | '/admin/contact-messages'
    | '/admin/distribution-slips'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/foundation'
    | '/admin/gallery'
    | '/admin/help-requests'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/volunteers'
    | '/m/$code'
    | '/v/$code'
    | '/admin'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/activities'
    | '/admin'
    | '/contact'
    | '/donate'
    | '/donations'
    | '/events'
    | '/forgot-password'
    | '/gallery'
    | '/help'
    | '/login'
    | '/my-membership'
    | '/notices'
    | '/reset-password'
    | '/track'
    | '/zakat-calculator'
    | '/zakat-guide'
    | '/_authenticated/membership'
    | '/activities/new'
    | '/admin/activities'
    | '/admin/activity-logs'
    | '/admin/committee'
    | '/admin/contact-messages'
    | '/admin/distribution-slips'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/foundation'
    | '/admin/gallery'
    | '/admin/help-requests'
    | '/admin/members'
    | '/admin/notices'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sms'
    | '/admin/volunteers'
    | '/m/$code'
    | '/v/$code'
    | '/admin/'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DonationsRoute: typeof DonationsRoute
  EventsRoute: typeof EventsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MyMembershipRoute: typeof MyMembershipRoute
  NoticesRoute: typeof NoticesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrackRoute: typeof TrackRoute
  ZakatCalculatorRoute: typeof ZakatCalculatorRoute
  ZakatGuideRoute: typeof ZakatGuideRoute
  MCodeRoute: typeof MCodeRoute
  VCodeRoute: typeof VCodeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakat-guide': {
      id: '/zakat-guide'
      path: '/zakat-guide'
      fullPath: '/zakat-guide'
      preLoaderRoute: typeof ZakatGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat-calculator': {
      id: '/zakat-calculator'
      path: '/zakat-calculator'
      fullPath: '/zakat-calculator'
      preLoaderRoute: typeof ZakatCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-membership': {
      id: '/my-membership'
      path: '/my-membership'
      fullPath: '/my-membership'
      preLoaderRoute: typeof MyMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v/$code': {
      id: '/v/$code'
      path: '/v/$code'
      fullPath: '/v/$code'
      preLoaderRoute: typeof VCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$code': {
      id: '/m/$code'
      path: '/m/$code'
      fullPath: '/m/$code'
      preLoaderRoute: typeof MCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sms': {
      id: '/admin/sms'
      path: '/sms'
      fullPath: '/admin/sms'
      preLoaderRoute: typeof AdminSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help-requests': {
      id: '/admin/help-requests'
      path: '/help-requests'
      fullPath: '/admin/help-requests'
      preLoaderRoute: typeof AdminHelpRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/foundation': {
      id: '/admin/foundation'
      path: '/foundation'
      fullPath: '/admin/foundation'
      preLoaderRoute: typeof AdminFoundationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distribution-slips': {
      id: '/admin/distribution-slips'
      path: '/distribution-slips'
      fullPath: '/admin/distribution-slips'
      preLoaderRoute: typeof AdminDistributionSlipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-messages': {
      id: '/admin/contact-messages'
      path: '/contact-messages'
      fullPath: '/admin/contact-messages'
      preLoaderRoute: typeof AdminContactMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/committee': {
      id: '/admin/committee'
      path: '/committee'
      fullPath: '/admin/committee'
      preLoaderRoute: typeof AdminCommitteeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activities': {
      id: '/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof AdminActivitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ActivitiesRouteChildren {
  ActivitiesNewRoute: typeof ActivitiesNewRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesNewRoute: ActivitiesNewRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

interface AdminRouteChildren {
  AdminActivitiesRoute: typeof AdminActivitiesRoute
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminCommitteeRoute: typeof AdminCommitteeRoute
  AdminContactMessagesRoute: typeof AdminContactMessagesRoute
  AdminDistributionSlipsRoute: typeof AdminDistributionSlipsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFoundationRoute: typeof AdminFoundationRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHelpRequestsRoute: typeof AdminHelpRequestsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSmsRoute: typeof AdminSmsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivitiesRoute: AdminActivitiesRoute,
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminCommitteeRoute: AdminCommitteeRoute,
  AdminContactMessagesRoute: AdminContactMessagesRoute,
  AdminDistributionSlipsRoute: AdminDistributionSlipsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFoundationRoute: AdminFoundationRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHelpRequestsRoute: AdminHelpRequestsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSmsRoute: AdminSmsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DonationsRoute: DonationsRoute,
  EventsRoute: EventsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MyMembershipRoute: MyMembershipRoute,
  NoticesRoute: NoticesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrackRoute: TrackRoute,
  ZakatCalculatorRoute: ZakatCalculatorRoute,
  ZakatGuideRoute: ZakatGuideRoute,
  MCodeRoute: MCodeRoute,
  VCodeRoute: VCodeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
